#!/bin/bash
echo "=== RHVM Access Information ==="
echo ""
echo "Web Console Access:"
echo "URL: https://$(hostname -f):443/ovirt-engine/"
echo "Default Username: admin@internal"
echo "Default Password: [Set during installation]"
echo ""
echo "Server Details:"
echo "Hostname: $(hostname -f)"
echo "IP Address: $(hostname -I | awk '{print $1}')"
echo ""
echo "SSL Certificate Information:"
echo "Certificate file: /etc/pki/ovirt-engine/certs/apache.cer"
echo "CA Certificate: /etc/pki/ovirt-engine/ca.pem"
echo ""
echo "To access the web console:"
echo "1. Open a web browser"
echo "2. Navigate to: https://$(hostname -f):443/ovirt-engine/"
echo "3. Accept the SSL certificate (if prompted)"
echo "4. Login with admin@internal and your password"
